### ISSUE TITLE
How do I analyze a site with login

### ISSUE THREAD

**Issue by JesperNoerregaard** [TheJaredWilcurt/UGUI-pa11y#35]
Our websites requires a login.

How do I check sites that are only available when someone is logged in?

**Comment by TheJaredWilcurt** [comment]
Unfortunately, due to the simple/straightforward nature of Koa11y, you can't.....



.... YET!

We are working on adding in "Actions" into Koa11y 4. It will let you set up a series of actions like "Click on this", "Wait for that", "Type this in", "Wait for new page to load". We are currently in the design phase for this feature. It will be in the next release. However that may not be for a while as our latest release just happened and we are going to be doing a major redesign of Koa11y for version 4. So that will take some time.

If you need access to the actions now, you can use [Pa11y](http://pa11y.org), which is a command line utility. It's what Koa11y runs under that hood.

I'm going to close this ticket and merge it with #27.
